# Generated by Django 3.1.4 on 2020-12-11 07:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spotify',
            fields=[
                ('acousticness', models.FloatField()),
                ('artists', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('danceability', models.FloatField()),
                ('duration_ms', models.IntegerField()),
                ('energy', models.FloatField()),
                ('explicit', models.IntegerField()),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('instrumentalness', models.FloatField()),
                ('key', models.IntegerField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('popularity', models.IntegerField()),
                ('release_date', models.DateField()),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('valence', models.FloatField()),
                ('year', models.CharField(max_length=100)),
            ],
        ),
    ]
